version: "2"
services:
  web1:
    build: ./node
    volumes:
      - "../node-code:/app"
    ports:
      - "3000:3000"
    command: nodemon -L bin/www
    links:
      - db
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - web1
    links:
      - web1:web1

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: example

  redis:
    image: redis
    ports:
        - "6379"
